// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image_block: dynamic(() => import("./ImageBlock")),
  tect_block: dynamic(() => import("./TextBlock")),
};
